### ISSUE TITLE
Add nix option to add typst packages by default

### ISSUE THREAD

**Issue by osbm** [loqusion/typix#32]
**Is your feature request related to a problem? Please describe.**
I think it would be a very helpful thing to add but. This is partly i couldnt manage to follow https://loqusion.github.io/typix/recipes/using-typst-packages.html (i am new to nix and is still dont fully understand `let` keyword)

If this doesnt seem feasible can you add an example that uses a typst packages to the examples folder?

Thank you so much for this flake it is awesome. :heart:

**Comment by loqusion** [comment]
Try [this example](https://github.com/loqusion/typix/blob/f9148a13f592a2c5691c51b072c1039e175f9b45/examples/typst-packages/flake.nix) and lmk if it works

**Comment by osbm** [comment]
This is awesome thanks a bunch. :sob: :100:

**Comment by osbm** [comment]
My flake: https://github.com/osbm/resume/blob/main/flake.nix

Mainly i just added fonts that are used.

There are a bunch of flake outputs.
nix develop, run, flake check, build. Very neat. 

You know i was trying to arrive to a solution that was readily available in typix (just to practice writing more nix code). But i crashed out during font management. (If a font exists in my system typst doesn't give error but if i try this same flake in docker it gives me error.) So i understood how much awesome the typix is.

Here is my attempt :sob: :sob: 🙏 https://github.com/osbm/resume/blob/96a46dfa3270e108f2f0bb2a50c1595367d8299e/flake.nix
